version: '3'
services:
  app:
    build: .
    env_file:
      - environment/directions.prod
    volumes:
      - '.:/opt/app'
    ports:
      - '8080:80'
    command: /bin/sh -c "bundle exec rerun --background -- rackup --port=80 -o 0.0.0.0 config.ru"
